theme:minima
title: Developers Arena
author: krpraveen0
email: pkec151015@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A complete blog to learn fullstack development using different programming languages.

# social links
github_username:  iampraveenkr 

show_excerpts: true # set to false to remove excerpts on the homepage
